# Generated by Django 5.2.4 on 2025-07-13 00:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Beneficio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('puntos_requeridos', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Cupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('tipo_descuento', models.CharField(choices=[('porcentaje', 'Porcentaje'), ('valor', 'Valor fijo')], max_length=10)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('usos_maximos', models.PositiveIntegerField(default=1)),
                ('usos_actuales', models.PositiveIntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_expiracion', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Nivel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('puntos_minimos', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PerfilCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntos', models.PositiveIntegerField(default=0)),
                ('pedidos_realizados', models.PositiveIntegerField(default=0)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('nivel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fidelizacion.nivel')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HistorialPuntos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('puntos', models.IntegerField()),
                ('motivo', models.CharField(max_length=255)),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos_puntos', to='fidelizacion.perfilcliente')),
            ],
        ),
        migrations.CreateModel(
            name='HistorialBeneficio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('beneficio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fidelizacion.beneficio')),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fidelizacion.perfilcliente')),
            ],
        ),
    ]
