# Generated by Django 5.2.3 on 2025-07-12 23:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='creado_en',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='nivel',
            field=models.CharField(choices=[('Bronce', 'Bronce'), ('Plata', 'Plata'), ('Oro', 'Oro'), ('Diamante', 'Diamante')], default='Bronce', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='nombre',
            field=models.CharField(default='sin nombre', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='puntos',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='rol',
            field=models.CharField(choices=[('cliente', 'Cliente'), ('admin', 'Administrador')], default='cliente', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='telefono',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
